### ISSUE TITLE
Fail on build

### ISSUE THREAD

**Issue by xiazeyu** [centreborelli/pypotree#4]
```
Collecting pypotree
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/de/29/4b469cd31b1707e03162f9786eee5ece345edfce5ca7d56ccc650719a579/pypotree-1.0.5.tar.gz (147 kB)
Requirement already satisfied: numpy in ./anaconda3/envs/ancient/lib/python3.6/site-packages (from pypotree) (1.19.5)
Building wheels for collected packages: pypotree
  Building wheel for pypotree (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /home/yladmin/anaconda3/envs/ancient/bin/python -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-luii003a/pypotree_b97f10bae2d04f238430213616abd612/setup.py'"'"'; __file__='"'"'/tmp/pip-install-luii003a/pypotree_b97f10bae2d04f238430213616abd612/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-0mbyc738
       cwd: /tmp/pip-install-luii003a/pypotree_b97f10bae2d04f238430213616abd612/
  Complete output (58 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib
  copying pypotree.py -> build/lib
  running egg_info
  writing pypotree.egg-info/PKG-INFO
  writing dependency_links to pypotree.egg-info/dependency_links.txt
  writing requirements to pypotree.egg-info/requires.txt
  writing top-level names to pypotree.egg-info/top_level.txt
  reading manifest file 'pypotree.egg-info/SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  writing manifest file 'pypotree.egg-info/SOURCES.txt'
  git clone https://github.com/cmla/PotreeConverter.git src/potreeconverter
  Cloning to 'src/potreeconverter'...
  cd src/potreeconverter && make PotreeConverter
  make[1]: Entering “/tmp/pip-install-luii003a/pypotree_b97f10bae2d04f238430213616abd612/src/potreeconverter”
  cd LAStools/LASzip && \
  mkdir -p build && cd build && \
  CC="cc" CXX="g++" cmake -DCMAKE_BUILD_TYPE=Release .. \
        -DCMAKE_C_COMPILER="cc" -DCMAKE_CXX_COMPILER="g++" && \
  make -j
  /bin/sh: 3: cmake: not found
  Makefile:12: recipe for target 'LASzip' failed
  make[1]: *** [LASzip] Error 127
  make[1]: Leaving “/tmp/pip-install-luii003a/pypotree_b97f10bae2d04f238430213616abd612/src/potreeconverter”
  Makefile:11: recipe for target 'binpot' failed
  make: *** [binpot] Error 2
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-install-luii003a/pypotree_b97f10bae2d04f238430213616abd612/setup.py", line 50, in <module>
      zip_safe=False)
    File "/home/yladmin/anaconda3/envs/ancient/lib/python3.6/site-packages/setuptools/__init__.py", line 153, in setup
      return distutils.core.setup(**attrs)
    File "/home/yladmin/anaconda3/envs/ancient/lib/python3.6/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/home/yladmin/anaconda3/envs/ancient/lib/python3.6/distutils/dist.py", line 955, in run_commands
      self.run_command(cmd)
    File "/home/yladmin/anaconda3/envs/ancient/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/home/yladmin/anaconda3/envs/ancient/lib/python3.6/site-packages/wheel/bdist_wheel.py", line 299, in run
      self.run_command('build')
    File "/home/yladmin/anaconda3/envs/ancient/lib/python3.6/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/home/yladmin/anaconda3/envs/ancient/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/home/yladmin/anaconda3/envs/ancient/lib/python3.6/distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/home/yladmin/anaconda3/envs/ancient/lib/python3.6/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/home/yladmin/anaconda3/envs/ancient/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/tmp/pip-install-luii003a/pypotree_b97f10bae2d04f238430213616abd612/setup.py", line 28, in run
      subprocess.check_call("make", shell=True)
    File "/home/yladmin/anaconda3/envs/ancient/lib/python3.6/subprocess.py", line 311, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command 'make' returned non-zero exit status 2.
  ----------------------------------------
  ERROR: Failed building wheel for pypotree
  Running setup.py clean for pypotree
Failed to build pypotree
Installing collected packages: pypotree
    Running setup.py install for pypotree ... error
    ERROR: Command errored out with exit status 1:
     command: /home/yladmin/anaconda3/envs/ancient/bin/python -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-luii003a/pypotree_b97f10bae2d04f238430213616abd612/setup.py'"'"'; __file__='"'"'/tmp/pip-install-luii003a/pypotree_b97f10bae2d04f238430213616abd612/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-gnvtultp/install-record.txt --single-version-externally-managed --compile --install-headers /home/yladmin/anaconda3/envs/ancient/include/python3.6m/pypotree
         cwd: /tmp/pip-install-luii003a/pypotree_b97f10bae2d04f238430213616abd612/
    Complete output (49 lines):
    running install
    running build
    running build_py
    creating build
    creating build/lib
    copying pypotree.py -> build/lib
    running egg_info
    writing pypotree.egg-info/PKG-INFO
    writing dependency_links to pypotree.egg-info/dependency_links.txt
    writing requirements to pypotree.egg-info/requires.txt
    writing top-level names to pypotree.egg-info/top_level.txt
    reading manifest file 'pypotree.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    writing manifest file 'pypotree.egg-info/SOURCES.txt'
    git clone https://github.com/cmla/PotreeConverter.git src/potreeconverter
    fatal: Target path 'src/potreeconverter' already exists, and is not empty。
    Makefile:11: recipe for target 'binpot' failed
    make: *** [binpot] Error 128
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-luii003a/pypotree_b97f10bae2d04f238430213616abd612/setup.py", line 50, in <module>
        zip_safe=False)
      File "/home/yladmin/anaconda3/envs/ancient/lib/python3.6/site-packages/setuptools/__init__.py", line 153, in setup
        return distutils.core.setup(**attrs)
      File "/home/yladmin/anaconda3/envs/ancient/lib/python3.6/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/home/yladmin/anaconda3/envs/ancient/lib/python3.6/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/home/yladmin/anaconda3/envs/ancient/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/home/yladmin/anaconda3/envs/ancient/lib/python3.6/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/home/yladmin/anaconda3/envs/ancient/lib/python3.6/distutils/command/install.py", line 545, in run
        self.run_command('build')
      File "/home/yladmin/anaconda3/envs/ancient/lib/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/home/yladmin/anaconda3/envs/ancient/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/home/yladmin/anaconda3/envs/ancient/lib/python3.6/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/home/yladmin/anaconda3/envs/ancient/lib/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/home/yladmin/anaconda3/envs/ancient/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/tmp/pip-install-luii003a/pypotree_b97f10bae2d04f238430213616abd612/setup.py", line 28, in run
        subprocess.check_call("make", shell=True)
      File "/home/yladmin/anaconda3/envs/ancient/lib/python3.6/subprocess.py", line 311, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command 'make' returned non-zero exit status 2.
    ----------------------------------------
ERROR: Command errored out with exit status 1: /home/yladmin/anaconda3/envs/ancient/bin/python -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-luii003a/pypotree_b97f10bae2d04f238430213616abd612/setup.py'"'"'; __file__='"'"'/tmp/pip-install-luii003a/pypotree_b97f10bae2d04f238430213616abd612/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-gnvtultp/install-record.txt --single-version-externally-managed --compile --install-headers /home/yladmin/anaconda3/envs/ancient/include/python3.6m/pypotree Check the logs for full command output.
```

**Comment by gfacciol** [comment]
Hi, it seems that you're missing some dependencies, at least cmake: 
    /bin/sh: 3: cmake: not found

**Comment by xiazeyu** [comment]
> Hi, it seems that you're missing some dependencies, at least cmake:
> /bin/sh: 3: cmake: not found

Thanks for that. I this this can be fixed by install fixed `apt-get install cmake`.
